### PR TITLE
Fixed race condition between `mp_exec_move` and `mp_aline`

### LINKED ISSUE #396: "msg":"Internal error - mp_exec_move()"
@justinclift 
I seem to get that error randomly what causes it? The comments in the code say it should never happen.

 if (bf->bf_func == NULL) {
        return(cm_panic(STAT_INTERNAL_ERROR, "mp_exec_move()")); // never supposed to get here
    }

### PR DESCRIPTION
**Pull request by ep1cman**
There exists a race condition between `mp_exec_move` and `mp_aline`.
When `mp_aline` is modifying a buffer it is possible for the timer interrupt to trigger `mp_exec_move` halfway though the buffer being constructed.

This should be guarded against by using `mp_commit_write_buffer` however, `mp_get_run_buffer` does not properly check if it able to get the run buffer, if the buffer remaining is the one being written to. Both `MP_BUFFER_EMPTY` and `MP_BUFFER_INITIALIZING` both indicate that the buffer should not be used. 

Fixes #396 

Also, while I was investigating the bug, I discovered a nazi related joke, which as a person of Polish decent, I find distasteful and have removed it.

Signed-off-by: Sebastian Goscik <sebastian.goscik@arm.com>

### CODE REVIEW

File: g2core/planner.h [hunk 1]
```diff
@@ -174,8 +174,6 @@ typedef enum {                      // bf->buffer_state values in incresing orde
     MP_BUFFER_BACK_PLANNED,         // buffer ready for final planning; velocities have been set
     MP_BUFFER_FULLY_PLANNED,        // buffer fully planned. May still be replanned
     MP_BUFFER_RUNNING,              // current running buffer
-    MP_BUFFER_POLAND,               // Hitler used Poland as a buffer state
```
Comment (justinclift) [inline g2core/planner.h:177]: Fair enough.  These two enums don't seem to be used anywhere anyway. :smile:

Guess Rob was in a weird mood or something when writing this. :confused:

**Comment by justinclift** [comment]
Thanks for this @ep1cman! @MitchBradley does this PR look ok to you?  I'm not the right person to review it from a technical perspective.  I **can** hit the Merge button through, if you reckon it's good. :smile:

That Travis failure seems like either a problem with the Travis infrastructure, or our .travis.yml may need updating.  Not sure which yet.  If it keeps happening, we'll need to investigate.

**Comment by MitchBradley** [comment]
I think it is good.  It certainly seems to fix a known and observable problem, and if it should cause other problems in the future, it would be easy to revert, since the change is small and isolated.

**Comment by justinclift** [comment]
Thanks, merged. :smile:

**Comment by giseburt** [comment]
This looks good, thank you @ep1cman.

My apologies for the Poland reference. I didn’t put it in, but saw it and didn’t remove it either. If I had any sense of it being any more than a historical reference then I would have removed it immediately.
